name: Releases Test Catalog Cleanup
on:
  schedule:
    - cron: '38 0 1 * *'
  workflow_dispatch:
jobs:
  cleanup:
    uses: giantswarm/app-catalog-cleanup-tool/.github/workflows/cleanup.yaml@88fdd9bc174f3e027fe26f7a9424ff97e4add365 # main
    with:
      delete-before: "1 month"
      dry-run: false
